name: Android-Чтосмотреть-Xəzinəsandığı
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 22,23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-宝箱】'
        run: |
          
          node Android-Чтосмотреть-Xəzinəsandığı.js
