name: Android-Чтосмотреть-打卡
on:
  workflow_dispatch:
  schedule:
    - cron: '3 5,8,9 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Saatdaxilolun】'
        run: |
          
          node Android-Чтосмотреть-Saatdaxilolun.js
        env:
          zq_cookie: ${{ secrets.zq_cookie }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
